workflows:
  build-ios-ipa:
    name: Build iOS IPA (Unsigned)
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      vars:
        BUNDLE_ID: "com.filipnygg.habittracker"
        APP_NAME: "Habit Tracker"
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Build iOS IPA (unsigned)
        script: |
          flutter build ipa --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - filny@live.se
